//! Deterministic clean images and the degradations applied to them.
//!
//! Every fixture starts from a known clean image, so the original is available
//! as ground truth and restoration can be scored rather than admired. Each
//! degradation is reproducible from a seed.
//!
//! These are honest about being synthetic. A Gaussian field is not a sensor, a
//! block-quantised fixture is not a JPEG encoder, and a drawn line is not a
//! scratch on a print. They are good enough to prove an algorithm does what it
//! claims on the degradation it was handed, and that is what they are used for.
use crate::color::{FloatImage, FloatRgba};

use super::metrics::Noise;

/// A clean test scene with the features restoration has to respect.
///
/// Deliberately contains all four things that break naive algorithms: large
/// flat regions (where noise is obvious), hard edges (which blur destroys),
/// thin lines (which denoise erases), and a smooth gradient (where banding and
/// blocking show up).
pub fn scene(width: u32, height: u32) -> FloatImage {
    let mut image = FloatImage::blank(width, height, FloatRgba::TRANSPARENT).unwrap();
    let (w, h) = (width as f32, height as f32);
    for y in 0..height {
        for x in 0..width {
            let (fx, fy) = (x as f32 / w, y as f32 / h);
            let mut colour = if fy < 0.25 {
                // Flat panels of three different levels.
                let level = [0.15f32, 0.5, 0.85][(fx * 3.0) as usize % 3];
                [level, level, level]
            } else if fy < 0.5 {
                // A horizontal gradient, for banding and blocking.
                [fx, fx * 0.75 + 0.1, 1.0 - fx * 0.6]
            } else if fy < 0.75 {
                // Hard vertical edges of alternating contrast.
                let bar = ((fx * 8.0) as u32).is_multiple_of(2);
                if bar {
                    [0.9, 0.85, 0.2]
                } else {
                    [0.1, 0.15, 0.6]
                }
            } else {
                // Fine texture plus single-pixel lines.
                let fine = (((x / 2) + (y / 2)) % 2) as f32 * 0.12;
                let line = if x % 9 == 0 || y % 11 == 0 { 0.45 } else { 0.0 };
                [0.35 + fine + line, 0.4 + fine, 0.45 + fine + line * 0.5]
            };
            for channel in &mut colour {
                *channel = channel.clamp(0.0, 1.0);
            }
            image.pixels_mut()[(y * width + x) as usize] =
                FloatRgba::new(colour[0], colour[1], colour[2], 1.0);
        }
    }
    image
}

/// Additive Gaussian noise, the same sigma on every channel.
pub fn gaussian_noise(image: &FloatImage, sigma: f32, seed: u64) -> FloatImage {
    let mut rng = Noise::new(seed);
    let mut out = image.clone();
    for pixel in out.pixels_mut() {
        *pixel = FloatRgba::new(
            pixel.red + rng.normal() * sigma,
            pixel.green + rng.normal() * sigma,
            pixel.blue + rng.normal() * sigma,
            pixel.alpha,
        );
    }
    out
}

/// Noise that is mostly chroma, as high-ISO colour noise is.
///
/// Generated by perturbing the two colour-difference axes and leaving luminance
/// nearly alone, so a luma/chroma-separated denoiser can be shown to help here
/// where a joint-RGB one cannot.
pub fn chroma_noise(image: &FloatImage, sigma: f32, seed: u64) -> FloatImage {
    let mut rng = Noise::new(seed);
    let mut out = image.clone();
    for pixel in out.pixels_mut() {
        let cb = rng.normal() * sigma;
        let cr = rng.normal() * sigma;
        // Opposed channel shifts move colour without moving luminance much.
        *pixel = FloatRgba::new(
            pixel.red + cr,
            pixel.green - (cb + cr) * 0.5,
            pixel.blue + cb,
            pixel.alpha,
        );
    }
    out
}

/// Salt-and-pepper impulses, as a fraction of pixels replaced by black or white.
pub fn impulse_noise(image: &FloatImage, fraction: f32, seed: u64) -> FloatImage {
    let mut rng = Noise::new(seed);
    let mut out = image.clone();
    for pixel in out.pixels_mut() {
        if rng.unit() < fraction {
            let level = if rng.unit() < 0.5 { 0.0 } else { 1.0 };
            *pixel = FloatRgba::new(level, level, level, pixel.alpha);
        }
    }
    out
}

/// Isolated hot, dead and stuck pixels at reproducible positions.
///
/// Returns the image and the coordinates that were damaged, so a detector can
/// be scored on what it found and what it missed rather than on a total.
pub fn sensor_defects(
    image: &FloatImage,
    count: usize,
    seed: u64,
) -> (FloatImage, Vec<(u32, u32)>) {
    let mut rng = Noise::new(seed);
    let mut out = image.clone();
    let (width, height) = image.dimensions();
    let mut placed = Vec::with_capacity(count);
    // Kept off the border so a detector is judged on its interior behaviour
    // rather than on edge clamping.
    for _ in 0..count {
        let x = 2 + (rng.unit() * (width.saturating_sub(4)) as f32) as u32;
        let y = 2 + (rng.unit() * (height.saturating_sub(4)) as f32) as u32;
        if placed.contains(&(x, y)) {
            continue;
        }
        let kind = rng.unit();
        let colour = if kind < 0.34 {
            FloatRgba::new(1.0, 1.0, 1.0, 1.0) // hot
        } else if kind < 0.67 {
            FloatRgba::new(0.0, 0.0, 0.0, 1.0) // dead
        } else {
            FloatRgba::new(1.0, 0.0, 0.0, 1.0) // stuck channel
        };
        out.pixels_mut()[(y * width + x) as usize] = colour;
        placed.push((x, y));
    }
    (out, placed)
}

/// Convolves with a normalised kernel, clamping at the border.
fn convolve(image: &FloatImage, kernel: &[(i32, i32, f32)]) -> FloatImage {
    let (width, height) = image.dimensions();
    let mut out = image.clone();
    let total: f32 = kernel.iter().map(|(_, _, w)| *w).sum();
    let total = if total.abs() < 1e-9 { 1.0 } else { total };
    for y in 0..height {
        for x in 0..width {
            let mut sum = [0.0f32; 3];
            for (dx, dy, weight) in kernel {
                let sx = (x as i32 + dx).clamp(0, width as i32 - 1) as u32;
                let sy = (y as i32 + dy).clamp(0, height as i32 - 1) as u32;
                let p = image.get(sx, sy).unwrap();
                sum[0] += p.red * weight;
                sum[1] += p.green * weight;
                sum[2] += p.blue * weight;
            }
            let alpha = image.get(x, y).unwrap().alpha;
            out.pixels_mut()[(y * width + x) as usize] =
                FloatRgba::new(sum[0] / total, sum[1] / total, sum[2] / total, alpha);
        }
    }
    out
}

/// The exact kernel `defocus_blur` applies, so a deconvolution can be tested
/// against the blur it is supposed to invert rather than against a guess.
pub fn defocus_kernel(radius: f32) -> Vec<(i32, i32, f32)> {
    let reach = radius.ceil().max(1.0) as i32;
    let mut kernel = Vec::new();
    for dy in -reach..=reach {
        for dx in -reach..=reach {
            let distance = ((dx * dx + dy * dy) as f32).sqrt();
            // A disc with a soft edge, which is what an out-of-focus point
            // spreads into, rather than a Gaussian.
            let weight = if distance <= radius {
                1.0
            } else if distance <= radius + 1.0 {
                radius + 1.0 - distance
            } else {
                0.0
            };
            if weight > 0.0 {
                kernel.push((dx, dy, weight));
            }
        }
    }
    kernel
}

/// Out-of-focus blur with a disc kernel.
pub fn defocus_blur(image: &FloatImage, radius: f32) -> FloatImage {
    convolve(image, &defocus_kernel(radius))
}

/// The exact kernel `motion_blur` applies.
pub fn motion_kernel(angle_degrees: f32, distance: f32) -> Vec<(i32, i32, f32)> {
    let steps = distance.round().max(1.0) as i32;
    let radians = angle_degrees.to_radians();
    let (dx, dy) = (radians.cos(), radians.sin());
    let mut kernel = Vec::new();
    // Sampled along the line and accumulated per integer offset, so the kernel
    // is exactly what the blur applies.
    for step in -(steps / 2)..=(steps / 2) {
        let x = (dx * step as f32).round() as i32;
        let y = (dy * step as f32).round() as i32;
        match kernel.iter_mut().find(|(kx, ky, _)| *kx == x && *ky == y) {
            Some((_, _, weight)) => *weight += 1.0,
            None => kernel.push((x, y, 1.0f32)),
        }
    }
    kernel
}

/// Linear motion blur at an angle.
pub fn motion_blur(image: &FloatImage, angle_degrees: f32, distance: f32) -> FloatImage {
    convolve(image, &motion_kernel(angle_degrees, distance))
}

/// Block-quantised degradation standing in for JPEG artifacts.
///
/// This is emphatically **not** a JPEG encoder: it quantises each 8x8 block's
/// mean and adds a graded per-block offset, producing blocking and a little
/// ringing at block edges. It exercises a de-blocking algorithm's ability to
/// find and soften an origin-anchored 8-pixel grid, which is the property that
/// matters, without pretending to model DCT quantisation tables.
pub fn block_artifacts(image: &FloatImage, strength: f32) -> FloatImage {
    let (width, height) = image.dimensions();
    let mut out = image.clone();
    for by in (0..height).step_by(8) {
        for bx in (0..width).step_by(8) {
            let (mut sum, mut count) = ([0.0f32; 3], 0.0f32);
            for y in by..(by + 8).min(height) {
                for x in bx..(bx + 8).min(width) {
                    let p = image.get(x, y).unwrap();
                    sum[0] += p.red;
                    sum[1] += p.green;
                    sum[2] += p.blue;
                    count += 1.0;
                }
            }
            let mean = [sum[0] / count, sum[1] / count, sum[2] / count];
            // Coarsely quantise the block mean, which is what produces visible
            // steps between neighbouring blocks. More strength means *fewer*
            // levels; the obvious `32 / strength` gets this backwards and makes
            // a strong setting quantise more finely than a weak one.
            let levels = (4.0 + (1.0 - strength.clamp(0.0, 1.0)) * 60.0).max(2.0);
            let quantised = mean.map(|v| (v * levels).round() / levels);
            for y in by..(by + 8).min(height) {
                for x in bx..(bx + 8).min(width) {
                    let p = image.get(x, y).unwrap();
                    let blended = |original: f32, block_mean: f32, block_q: f32| {
                        original + (block_q - block_mean) * strength
                    };
                    out.pixels_mut()[(y * width + x) as usize] = FloatRgba::new(
                        blended(p.red, mean[0], quantised[0]),
                        blended(p.green, mean[1], quantised[1]),
                        blended(p.blue, mean[2], quantised[2]),
                        p.alpha,
                    );
                }
            }
        }
    }
    out
}

/// A smooth multiplicative illumination falloff, as a scan or a flash gives.
pub fn uneven_illumination(image: &FloatImage, strength: f32) -> FloatImage {
    let (width, height) = image.dimensions();
    let mut out = image.clone();
    for y in 0..height {
        for x in 0..width {
            let nx = x as f32 / width as f32 - 0.5;
            let ny = y as f32 / height as f32 - 0.5;
            let falloff = 1.0 - strength * (nx * nx + ny * ny) * 2.0;
            let p = image.get(x, y).unwrap();
            out.pixels_mut()[(y * width + x) as usize] = FloatRgba::new(
                p.red * falloff,
                p.green * falloff,
                p.blue * falloff,
                p.alpha,
            );
        }
    }
    out
}

/// Age-faded print: compressed contrast, lifted blacks and a warm cast.
pub fn faded(image: &FloatImage, amount: f32) -> FloatImage {
    let mut out = image.clone();
    for pixel in out.pixels_mut() {
        let compress = |v: f32, cast: f32| {
            let lifted = v * (1.0 - amount * 0.55) + amount * 0.28;
            lifted * (1.0 - amount * 0.2) + cast * amount * 0.2
        };
        *pixel = FloatRgba::new(
            compress(pixel.red, 0.95),
            compress(pixel.green, 0.80),
            compress(pixel.blue, 0.55),
            pixel.alpha,
        );
    }
    out
}

/// Small opaque specks, as dust on a scanner platen.
pub fn dust(image: &FloatImage, count: usize, seed: u64) -> (FloatImage, Vec<(u32, u32)>) {
    let mut rng = Noise::new(seed);
    let (width, height) = image.dimensions();
    let mut out = image.clone();
    let mut placed = Vec::new();
    for _ in 0..count {
        let x = 3 + (rng.unit() * (width.saturating_sub(6)) as f32) as u32;
        let y = 3 + (rng.unit() * (height.saturating_sub(6)) as f32) as u32;
        let radius = if rng.unit() < 0.6 { 0 } else { 1 };
        let level = if rng.unit() < 0.5 { 0.02 } else { 0.98 };
        for dy in -radius..=radius {
            for dx in -radius..=radius {
                let sx = (x as i32 + dx).clamp(0, width as i32 - 1) as u32;
                let sy = (y as i32 + dy).clamp(0, height as i32 - 1) as u32;
                let alpha = out.get(sx, sy).unwrap().alpha;
                out.pixels_mut()[(sy * width + sx) as usize] =
                    FloatRgba::new(level, level, level, alpha);
            }
        }
        placed.push((x, y));
    }
    (out, placed)
}

/// Thin bright or dark lines, as scratches on a negative.
pub fn scratches(image: &FloatImage, count: usize, seed: u64) -> FloatImage {
    let mut rng = Noise::new(seed);
    let (width, height) = image.dimensions();
    let mut out = image.clone();
    for _ in 0..count {
        let x0 = (rng.unit() * width as f32) as i32;
        let y0 = (rng.unit() * height as f32) as i32;
        let angle = rng.unit() * std::f32::consts::TAU;
        let length = (height as f32 * (0.3 + rng.unit() * 0.5)) as i32;
        let level = if rng.unit() < 0.5 { 0.03 } else { 0.97 };
        for step in 0..length {
            let x = x0 + (angle.cos() * step as f32) as i32;
            let y = y0 + (angle.sin() * step as f32) as i32;
            if x < 0 || y < 0 || x >= width as i32 || y >= height as i32 {
                continue;
            }
            let alpha = out.get(x as u32, y as u32).unwrap().alpha;
            out.pixels_mut()[(y as u32 * width + x as u32) as usize] =
                FloatRgba::new(level, level, level, alpha);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::super::metrics::{edge_retention, flat_area_noise, mse, psnr, ssim};
    use super::*;

    /// The scene has to contain the features it claims to, or every metric
    /// computed against it measures nothing in particular.
    #[test]
    fn the_scene_contains_flat_edge_and_texture_regions() {
        let image = scene(128, 128);
        assert_eq!(image.dimensions(), (128, 128));
        assert!(image.validate().is_ok());
        // Flat band at the top: a 3x3 neighbourhood with no variation exists.
        assert_eq!(flat_area_noise(&image, &image), 0.0);
        // Edge band: the image has gradient energy to retain.
        assert!((edge_retention(&image, &image) - 1.0).abs() < 1e-9);
        // Every pixel is a valid opaque colour.
        assert!(image
            .pixels()
            .iter()
            .all(|p| p.alpha == 1.0 && p.is_finite()));
    }

    /// Fixtures must be reproducible from a seed, or a failing case cannot be
    /// re-created and a benchmark cannot be compared across runs.
    #[test]
    fn every_degradation_is_reproducible_from_its_seed() {
        let clean = scene(64, 64);
        assert_eq!(
            gaussian_noise(&clean, 0.05, 11).pixels(),
            gaussian_noise(&clean, 0.05, 11).pixels()
        );
        assert_eq!(
            impulse_noise(&clean, 0.02, 5).pixels(),
            impulse_noise(&clean, 0.02, 5).pixels()
        );
        assert_eq!(
            chroma_noise(&clean, 0.05, 9).pixels(),
            chroma_noise(&clean, 0.05, 9).pixels()
        );
        assert_eq!(
            scratches(&clean, 3, 2).pixels(),
            scratches(&clean, 3, 2).pixels()
        );
        assert_eq!(
            sensor_defects(&clean, 20, 4).1,
            sensor_defects(&clean, 20, 4).1
        );
        // A different seed must actually differ, or the seed is being ignored.
        assert_ne!(
            gaussian_noise(&clean, 0.05, 11).pixels(),
            gaussian_noise(&clean, 0.05, 12).pixels()
        );
    }

    /// Each degradation must actually degrade, by the metric that describes it.
    #[test]
    fn each_degradation_moves_the_metric_it_is_meant_to() {
        let clean = scene(96, 96);

        let noisy = gaussian_noise(&clean, 0.06, 1);
        assert!(
            flat_area_noise(&clean, &noisy) > 0.03,
            "gaussian noise did not raise flat-area noise"
        );

        let blurred = defocus_blur(&clean, 2.0);
        assert!(
            edge_retention(&clean, &blurred) < 0.7,
            "defocus blur did not reduce edge energy"
        );

        let moved = motion_blur(&clean, 30.0, 9.0);
        assert!(
            edge_retention(&clean, &moved) < 0.9,
            "motion blur did not reduce edge energy"
        );

        let blocked = block_artifacts(&clean, 0.8);
        assert!(
            psnr(&clean, &blocked) < 40.0,
            "block artifacts did not measurably damage the image"
        );

        let dim = uneven_illumination(&clean, 0.6);
        assert!(
            mse(&clean, &dim) > 1e-4,
            "illumination falloff had no effect"
        );

        let old = faded(&clean, 0.8);
        assert!(ssim(&clean, &old) < 0.99, "fading had no structural effect");

        let (defects, placed) = sensor_defects(&clean, 40, 3);
        assert!(!placed.is_empty());
        assert!(
            placed
                .iter()
                .any(|&(x, y)| defects.get(x, y) != clean.get(x, y)),
            "no sensor defect was actually written"
        );
    }

    /// A deconvolution can only be judged against the kernel that was applied,
    /// so the published kernel must be the one the blur uses.
    #[test]
    fn published_kernels_match_the_blur_they_describe() {
        let clean = scene(48, 48);
        for (name, blurred, kernel) in [
            ("defocus", defocus_blur(&clean, 2.0), defocus_kernel(2.0)),
            (
                "motion",
                motion_blur(&clean, 45.0, 7.0),
                motion_kernel(45.0, 7.0),
            ),
        ] {
            let manual = convolve(&clean, &kernel);
            assert_eq!(
                manual.pixels(),
                blurred.pixels(),
                "the published {name} kernel is not the one applied"
            );
            let total: f32 = kernel.iter().map(|(_, _, w)| *w).sum();
            assert!(total > 0.0, "the {name} kernel sums to zero");
        }
    }
}
